'use client'
import { useState } from 'react'

interface Perspectives { fanView: string; criticView: string; insiderView: string }

const TABS = [
  { key: 'fanView',     icon: '💜', label: 'Fan View'         },
  { key: 'criticView',  icon: '🎯', label: 'Critic View'      },
  { key: 'insiderView', icon: '🤫', label: 'Industry Insider' },
] as const

export function PerspectiveEngine({
  articleId, title, excerpt,
}: { articleId: number; title: string; excerpt?: string }) {
  const cacheKey = `perspectives_${articleId}`
  const [data,     setData]     = useState<Perspectives | null>(null)
  const [loading,  setLoading]  = useState(false)
  const [active,   setActive]   = useState<'fanView' | 'criticView' | 'insiderView'>('fanView')
  const [error,    setError]    = useState('')

  async function load() {
    const cached = localStorage.getItem(cacheKey)
    if (cached) { try { setData(JSON.parse(cached)); return } catch { /* re-fetch */ } }
    setLoading(true); setError('')
    try {
      const r = await fetch('/api/articles/perspectives', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, excerpt }),
      })
      const d = await r.json() as Perspectives
      if (!d.fanView) throw new Error('Empty response')
      localStorage.setItem(cacheKey, JSON.stringify(d))
      setData(d)
    } catch { setError('Could not load perspectives — try again.') }
    setLoading(false)
  }

  if (!data && !loading) {
    return (
      <div style={{
        background: '#0A0A0A', border: '1px solid #1E1E1E',
        borderRadius: '16px', padding: '20px 24px', margin: '28px 0',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
          <div>
            <p style={{ fontSize: '0.62rem', fontWeight: 900, color: '#D4AF37', textTransform: 'uppercase', letterSpacing: '0.12em', margin: 0 }}>
              AI Perspectives
            </p>
            <p style={{ fontSize: '0.78rem', color: '#555', margin: '2px 0 0' }}>
              Fan View · Critic View · Industry Insider
            </p>
          </div>
          <button onClick={load} style={{
            marginLeft: 'auto',
            background: 'linear-gradient(45deg, #D4AF37, #F0D060)',
            color: '#1A1A1A', border: 'none',
            padding: '8px 18px', borderRadius: '20px',
            fontSize: '0.72rem', fontWeight: 800, cursor: 'pointer',
            letterSpacing: '0.06em', textTransform: 'uppercase',
          }}>
            Get Perspectives ✨
          </button>
        </div>
        {error && <p style={{ fontSize: '0.72rem', color: '#EF4444', marginTop: '10px' }}>{error}</p>}
      </div>
    )
  }

  if (loading) {
    return (
      <div style={{ background: '#0A0A0A', border: '1px solid #1E1E1E', borderRadius: '16px', padding: '24px', margin: '28px 0', textAlign: 'center' }}>
        <p style={{ color: '#555', fontSize: '0.82rem' }}>✨ Generating perspectives…</p>
      </div>
    )
  }

  return (
    <div style={{ background: '#0A0A0A', border: '1px solid #1E1E1E', borderRadius: '16px', margin: '28px 0', overflow: 'hidden' }}>
      {/* Tabs */}
      <div style={{ display: 'flex', borderBottom: '1px solid #1E1E1E' }}>
        {TABS.map(tab => (
          <button
            key={tab.key}
            onClick={() => setActive(tab.key)}
            style={{
              flex: 1, padding: '12px 8px',
              background: active === tab.key ? '#111' : 'transparent',
              border: 'none', borderBottom: active === tab.key ? '2px solid #D4AF37' : '2px solid transparent',
              color: active === tab.key ? '#EEE' : '#555',
              fontSize: '0.68rem', fontWeight: 800, cursor: 'pointer',
              textTransform: 'uppercase', letterSpacing: '0.08em',
              transition: 'all 0.15s',
            }}
          >
            {tab.icon} {tab.label}
          </button>
        ))}
      </div>
      {/* Content */}
      <div style={{ padding: '20px 24px' }}>
        <p style={{ color: '#CCC', fontSize: '0.88rem', lineHeight: 1.7, margin: 0 }}>
          {data?.[active]}
        </p>
        <p style={{ fontSize: '0.6rem', color: '#333', marginTop: '14px', margin: '14px 0 0' }}>
          Generated by Camer360 AI · Not editorial opinion
        </p>
      </div>
    </div>
  )
}
